UplynkAdBreak and UplynkAd as a customData in SSAI
THEOplayer/android-connector pull request #33
Opened 2024-09-02 14:32 UTC by OlegRyz

This uses SSAI `Ad.customData` and `AdBreak.customData` fields to make UplynkAd and UplynkAdBreak field available for a user

2024-09-02 14:36 UTC, OlegRyz commented
This PR could be merged after we release 8.0.0 THEOplayer, since the API that it uses will be only available there

2024-09-06 10:59 UTC, hovig-theo approved these changes

2024-09-09 08:55 UTC, MattiasBuelens requested changes

2024-09-09 08:55 UTC, MattiasBuelens commented on connectors/uplynk/README.md
> +        theoplayerView.player.ads.currentAdBreak?.customData as UplynkAdBreak? ?: return
Same as above:
```suggestion
        theoplayerView.player.ads.currentAdBreak?.customData as? UplynkAdBreak ?: return
```

2024-09-09 09:05 UTC, OlegRyz commented on connectors/uplynk/README.md
> +        theoplayerView.player.ads.currentAds.firstOrNull()?.customData as UplynkAd? ?: return
Good point, I didn't think about this case

2024-09-09 09:10 UTC, MattiasBuelens approved these changes

2024-09-09 10:38 UTC, merged